name: CI
on: [push, pull_request]

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Check style with prettier
      run: npm run format-check

    - name: Run tests
      run: npm test

    - name: Check build artifact has been checked in
      run: npm run build && git diff --quiet
